name: Tests
on: pull_request
env:
  MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16 version
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test project
        run: npm test
